import { ArrowDown, ArrowUp, ArrowUpDown, MoreHorizontal } from 'lucide-react'
import { createPortal } from 'react-dom'
import { useEffect, useLayoutEffect, useRef, useState } from 'react'
import { EmployeeStatusBadge } from './EmployeeStatusBadge'
import { LoginStatusBadge } from './LoginStatusBadge'
import type { Employee, EmployeeSortField } from '../types/employee.types'

const columns: { label: string; field?: EmployeeSortField }[] = [{ label: 'Employee', field: 'FirstName' }, { label: 'Code', field: 'EmployeeCode' }, { label: 'Department' }, { label: 'Job title', field: 'JobTitle' }, { label: 'Manager' }, { label: 'Employment status', field: 'EmploymentStatus' }, { label: 'Login access' }]

export function EmployeeTable({ employees, sortBy, sortDirection, canManage, onSort, onView, onEdit, onDeactivate, onReactivate, onCreateLogin, onUpdateLogin, onDisableLogin, onEnableLogin }: { employees: Employee[]; sortBy: EmployeeSortField; sortDirection: 'asc' | 'desc'; canManage: boolean; onSort: (field: EmployeeSortField) => void; onView: (employee: Employee) => void; onEdit: (employee: Employee) => void; onDeactivate: (employee: Employee) => void; onReactivate: (employee: Employee) => void; onCreateLogin: (employee: Employee) => void; onUpdateLogin: (employee: Employee) => void; onDisableLogin: (employee: Employee) => void; onEnableLogin: (employee: Employee) => void }) {
  return <div className="department-table-wrap"><table className="department-table employee-table"><caption className="sr-only">Employees</caption><thead><tr>{columns.map((column) => <th scope="col" key={column.label}>{column.field ? <button type="button" className="sort-button" aria-label={`Sort by ${column.label}`} aria-pressed={sortBy === column.field} onClick={() => onSort(column.field!)}>{column.label}{sortBy === column.field ? sortDirection === 'asc' ? <ArrowUp size={14} aria-hidden="true" /> : <ArrowDown size={14} aria-hidden="true" /> : <ArrowUpDown size={14} aria-hidden="true" />}</button> : column.label}</th>)}<th scope="col" className="actions-column">Actions</th></tr></thead><tbody>{employees.map((employee) => <tr key={employee.id}><th scope="row"><div className="employee-cell"><span className="employee-avatar" aria-hidden="true">{employee.firstName[0]}{employee.lastName[0]}</span><span><strong>{employee.fullName}</strong><small>{employee.workEmail || 'No work email'}</small></span></div></th><td className="department-code">{employee.employeeCode}</td><td>{employee.department ? `${employee.department.code} · ${employee.department.name}` : '—'}</td><td>{employee.jobTitle || '—'}</td><td>{employee.manager?.fullName || '—'}</td><td><EmployeeStatusBadge status={employee.employmentStatus} active={employee.isActive} /></td><td><LoginStatusBadge login={employee.loginAccount} /></td><td className="actions-column"><EmployeeActionMenu employee={employee} canManage={canManage} onView={onView} onEdit={onEdit} onDeactivate={onDeactivate} onReactivate={onReactivate} onCreateLogin={onCreateLogin} onUpdateLogin={onUpdateLogin} onDisableLogin={onDisableLogin} onEnableLogin={onEnableLogin} /></td></tr>)}</tbody></table></div>
}

function EmployeeActionMenu({ employee, canManage, onView, onEdit, onDeactivate, onReactivate, onCreateLogin, onUpdateLogin, onDisableLogin, onEnableLogin }: { employee: Employee; canManage: boolean; onView: (employee: Employee) => void; onEdit: (employee: Employee) => void; onDeactivate: (employee: Employee) => void; onReactivate: (employee: Employee) => void; onCreateLogin: (employee: Employee) => void; onUpdateLogin: (employee: Employee) => void; onDisableLogin: (employee: Employee) => void; onEnableLogin: (employee: Employee) => void }) {
  const [open, setOpen] = useState(false); const [position, setPosition] = useState({ top: 0, left: 0 }); const triggerRef = useRef<HTMLButtonElement>(null); const menuRef = useRef<HTMLDivElement>(null)
  useLayoutEffect(() => { if (!open || !triggerRef.current || !menuRef.current) return; const trigger = triggerRef.current.getBoundingClientRect(); const menu = menuRef.current.getBoundingClientRect(); const top = trigger.bottom + 6 + menu.height <= window.innerHeight ? trigger.bottom + 6 : trigger.top - menu.height - 6; setPosition({ top: Math.max(8, top), left: Math.min(Math.max(8, trigger.right - menu.width), window.innerWidth - menu.width - 8) }) }, [open])
  useEffect(() => { if (!open) return; const outside = (event: MouseEvent) => { const target = event.target as Node; if (!triggerRef.current?.contains(target) && !menuRef.current?.contains(target)) setOpen(false) }; const key = (event: KeyboardEvent) => { if (event.key === 'Escape') { setOpen(false); triggerRef.current?.focus() } }; const scroll = () => setOpen(false); document.addEventListener('mousedown', outside); document.addEventListener('keydown', key); window.addEventListener('scroll', scroll, true); return () => { document.removeEventListener('mousedown', outside); document.removeEventListener('keydown', key); window.removeEventListener('scroll', scroll, true) } }, [open])
  const choose = (callback: () => void) => { setOpen(false); callback() }
  const active = employee.isActive
  return <><button ref={triggerRef} type="button" className="row-actions-trigger" aria-label={`Actions for ${employee.fullName}`} aria-expanded={open} onClick={() => setOpen((value) => !value)}><MoreHorizontal size={17} aria-hidden="true" /></button>{open && createPortal(<div ref={menuRef} className="row-actions-menu row-actions-menu-floating employee-actions-menu" role="menu" style={{ top: position.top, left: position.left }}><button type="button" role="menuitem" onClick={() => choose(() => onView(employee))}>View</button>{canManage && active && <button type="button" role="menuitem" onClick={() => choose(() => onEdit(employee))}>Edit</button>}{canManage && active && !employee.hasLoginAccount && <button type="button" role="menuitem" onClick={() => choose(() => onCreateLogin(employee))}>Create login</button>}{canManage && employee.hasLoginAccount && <button type="button" role="menuitem" onClick={() => choose(() => onUpdateLogin(employee))}>Update login</button>}{canManage && active && employee.hasLoginAccount && employee.loginAccount.isActive && <button type="button" role="menuitem" onClick={() => choose(() => onDisableLogin(employee))}>Disable login</button>}{canManage && active && employee.hasLoginAccount && !employee.loginAccount.isActive && <button type="button" role="menuitem" onClick={() => choose(() => onEnableLogin(employee))}>Enable login</button>}{canManage && (active ? <button type="button" role="menuitem" onClick={() => choose(() => onDeactivate(employee))}>Deactivate</button> : <button type="button" role="menuitem" onClick={() => choose(() => onReactivate(employee))}>Reactivate</button>)}</div>, document.body)}</>
}
