import { zodResolver } from '@hookform/resolvers/zod'
import { AlertTriangle, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import { useForm } from 'react-hook-form'
import { toast } from 'sonner'
import { Alert } from '../../../components/ui/Alert'
import { Button } from '../../../components/ui/Button'
import { mapServerValidation } from '../../auth/api/formErrors'
import { useEmployeeMutations } from '../hooks/useEmployeeMutations'
import { employeeLoginSchema, type EmployeeLoginFormValues, updateEmployeeLoginSchema, type UpdateEmployeeLoginFormValues } from '../schemas/employeeLoginSchema'
import { LoginStatusBadge } from './LoginStatusBadge'
import type { Employee, EmployeeFormOptions } from '../types/employee.types'
import type { ApiError } from '../../../lib/api/apiError'

type CloseProps = { onClose: () => void }
function Frame({ title, description, onClose, children }: CloseProps & { title: string; description: string; children: ReactNode }) {
  const panel = useRef<HTMLElement>(null)
  useEffect(() => { panel.current?.querySelector<HTMLElement>('button, input, select, textarea')?.focus(); const key = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; document.addEventListener('keydown', key); return () => document.removeEventListener('keydown', key) }, [onClose])
  return <div className="dialog-backdrop" role="presentation"><section ref={panel} className="dialog-panel" role="dialog" aria-modal="true" aria-labelledby="employee-dialog-title" aria-describedby="employee-dialog-description"><div className="dialog-header"><div><h2 id="employee-dialog-title">{title}</h2><p id="employee-dialog-description">{description}</p></div><button type="button" className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={18} /></button></div>{children}</section></div>
}
function errorMessage(error: unknown, fallback: string) { const value = error as ApiError; return value.status === 409 ? value.message || fallback : value.status === 403 ? 'You do not have permission to manage employees.' : fallback }
function RoleField({ options, value, onChange }: { options: EmployeeFormOptions['roles']; value: string; onChange: (value: string) => void }) { return <label className="form-field"><span>Role<span className="required-mark">*</span></span><select value={value} onChange={(event) => onChange(event.target.value)}><option value="">Select a role</option>{options.map((role) => <option value={role.id} key={role.id}>{role.name}</option>)}</select></label> }

export function EmployeeLifecycleDialog({ employee, action, onClose }: CloseProps & { employee: Employee; action: 'deactivate' | 'reactivate' }) {
  const { deactivate, reactivate } = useEmployeeMutations(); const [error, setError] = useState(''); const pending = deactivate.isPending || reactivate.isPending
  async function confirm() { setError(''); try { if (action === 'deactivate') await deactivate.mutateAsync(employee.id); else await reactivate.mutateAsync(employee.id); toast.success(action === 'deactivate' ? 'Employee deactivated.' : 'Employee reactivated.'); onClose() } catch (value) { setError(errorMessage(value, 'The employee lifecycle action could not be completed.')) } }
  return <Frame title={action === 'deactivate' ? 'Deactivate employee' : 'Reactivate employee'} description={action === 'deactivate' ? 'Employment and login access will be disabled. Existing records will be preserved.' : 'Reactivating employment does not automatically enable login access.'} onClose={onClose}><div className="confirm-copy"><AlertTriangle size={22} aria-hidden="true" /><p>{error || `${action === 'deactivate' ? 'Deactivate' : 'Reactivate'} ${employee.fullName}?`}</p></div><div className="dialog-actions"><Button type="button" variant="secondary" onClick={onClose} disabled={pending}>Cancel</Button><Button type="button" className={action === 'deactivate' ? 'button-danger' : undefined} onClick={() => void confirm()} disabled={pending}>{pending ? 'Working…' : action === 'deactivate' ? 'Deactivate' : 'Reactivate'}</Button></div></Frame>
}

export function EmployeeLoginDialog({ employee, action, options, onClose }: CloseProps & { employee: Employee; action: 'create' | 'update'; options: EmployeeFormOptions }) {
  const { createLogin, updateLogin } = useEmployeeMutations(); const isCreate = action === 'create'; const form = useForm<EmployeeLoginFormValues | UpdateEmployeeLoginFormValues>({ resolver: zodResolver(isCreate ? employeeLoginSchema : updateEmployeeLoginSchema), defaultValues: { userName: employee.loginAccount.userName ?? '', email: employee.loginAccount.email ?? employee.workEmail ?? '', password: '', confirmPassword: '', roleId: employee.loginAccount.roles.length ? options.roles.find((role) => employee.loginAccount.roles.includes(role.name))?.id ?? '' : '' } as EmployeeLoginFormValues })
  const [serverError, setServerError] = useState('')
  async function submit(values: EmployeeLoginFormValues | UpdateEmployeeLoginFormValues) { setServerError(''); try { if (isCreate) await createLogin.mutateAsync({ id: employee.id, request: values as EmployeeLoginFormValues }); else await updateLogin.mutateAsync({ id: employee.id, request: { userName: values.userName, email: values.email, roleId: values.roleId } }); toast.success(isCreate ? 'Login account created.' : 'Login account updated.'); onClose() } catch (value) { if (mapServerValidation(value, form.setError)) return; setServerError(errorMessage(value, isCreate ? 'The login account could not be created.' : 'The login account could not be updated.')) } }
  const errors = form.formState.errors as Record<string, { message?: string } | undefined>; const pending = createLogin.isPending || updateLogin.isPending
  return <Frame title={isCreate ? 'Create login account' : 'Update login account'} description={isCreate ? 'Create sign-in access for this active employee.' : 'Update username, email, and assigned role. Password changes are handled separately.'} onClose={onClose}><form className="department-form" onSubmit={(event) => void form.handleSubmit((values) => submit(values))(event)} noValidate>{serverError && <Alert className="form-alert">{serverError}</Alert>}<label className="form-field"><span>Username<span className="required-mark">*</span></span><input autoComplete="username" {...form.register('userName')} />{errors.userName?.message && <small className="field-error" role="alert">{errors.userName.message}</small>}</label><label className="form-field"><span>Email<span className="required-mark">*</span></span><input type="email" autoComplete="email" {...form.register('email')} />{errors.email?.message && <small className="field-error" role="alert">{errors.email.message}</small>}</label>{isCreate && <><label className="form-field"><span>Password<span className="required-mark">*</span></span><input type="password" autoComplete="new-password" {...form.register('password')} /><small className="password-hint">At least 8 characters with uppercase, lowercase, number, and special character.</small>{errors.password?.message && <small className="field-error" role="alert">{errors.password.message}</small>}</label><label className="form-field"><span>Confirm password<span className="required-mark">*</span></span><input type="password" autoComplete="new-password" {...form.register('confirmPassword')} />{errors.confirmPassword?.message && <small className="field-error" role="alert">{errors.confirmPassword.message}</small>}</label></>}<RoleField options={options.roles} value={form.watch('roleId')} onChange={(value) => form.setValue('roleId', value, { shouldDirty: true, shouldValidate: true })} />{errors.roleId?.message && <small className="field-error" role="alert">{errors.roleId.message}</small>}<div className="dialog-actions"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={pending}>{pending ? 'Saving…' : isCreate ? 'Create login account' : 'Save login changes'}</Button></div></form></Frame>
}

export function EmployeeLoginStateDialog({ employee, action, onClose }: CloseProps & { employee: Employee; action: 'disable' | 'enable' }) {
  const { disableLogin, enableLogin } = useEmployeeMutations(); const [error, setError] = useState(''); const pending = disableLogin.isPending || enableLogin.isPending
  async function confirm() { setError(''); try { if (action === 'disable') await disableLogin.mutateAsync(employee.id); else await enableLogin.mutateAsync(employee.id); toast.success(action === 'disable' ? 'Login disabled.' : 'Login enabled.'); onClose() } catch (value) { setError(errorMessage(value, 'The login access action could not be completed.')) } }
  return <Frame title={action === 'disable' ? 'Disable login access' : 'Enable login access'} description={action === 'disable' ? 'The employee remains active, but cannot sign in. Existing sessions will be revoked.' : 'Enable sign-in access without changing the existing password.'} onClose={onClose}><div className="confirm-copy"><LoginStatusBadge login={employee.loginAccount} /><p>{error || `${action === 'disable' ? 'Disable' : 'Enable'} login for ${employee.fullName}?`}</p></div><div className="dialog-actions"><Button type="button" variant="secondary" onClick={onClose} disabled={pending}>Cancel</Button><Button type="button" className={action === 'disable' ? 'button-danger' : undefined} onClick={() => void confirm()} disabled={pending}>{pending ? 'Working…' : action === 'disable' ? 'Disable login' : 'Enable login'}</Button></div></Frame>
}
