export type PagedResponse<T> = { items: T[]; page: number; pageSize: number; totalCount: number; totalPages: number; hasPreviousPage: boolean; hasNextPage: boolean }
export type OvertimeType = { id: string; code: string; name: string; description: string | null; payMultiplier: number; isPaid: boolean; isActive: boolean; rowVersion: string }
export type OvertimeProject = { id: string; code: string; name: string; description: string | null; isActive: boolean; rowVersion: string }
export type OvertimeSettings = { id: string; isEnabled: boolean; requireProject: boolean; requireAttendanceRecord: boolean; allowWorkingDayOvertime: boolean; allowRestDayOvertime: boolean; allowHolidayOvertime: boolean; allowMorningContinuation: boolean; allowPendingCancellation: boolean; workingDayEarliestStartTime: string; workingDayLatestEndTime: string; morningLatestEndTime: string; restDayEarliestStartTime: string; restDayLatestEndTime: string; maxMinutesPerRequest: number; maxMinutesPerWorkDate: number; minimumRequestMinutes: number; isActive: boolean; rowVersion: string }
export type OvertimeProjectOption = { id: string; code: string; name: string }
export type OvertimeTypeOption = { id: string; code: string; name: string; payMultiplier: number }
export type OvertimeSettingsOptions = { currentSettings: OvertimeSettings; activeProjects: OvertimeProjectOption[]; activeTypes: OvertimeTypeOption[] }
export type ApproverType = 1 | 2 | 3
export type OvertimeApprovalSettings = { id: string; isEnabled: boolean; requiredLevels: number; rowVersion: string }
export type ApproverEmployee = { id: string; employeeCode: string; fullName: string; jobTitle: string | null }
export type ApproverRole = { id: string; name: string; normalizedName: string }
export type ApprovalOptions = { employees: ApproverEmployee[]; roles: ApproverRole[]; approverTypes: ApproverType[]; supportedLevels: number[]; currentSettings: OvertimeApprovalSettings | null }
export type ApprovalLevel = { id: string; levelNumber: number; name: string; approverType: ApproverType; approverRole: ApproverRole | null; approverEmployee: ApproverEmployee | null; isActive: boolean; rowVersion: string }
export type TypeFilters = { search?: string; isActive?: boolean; isPaid?: boolean; page: number; pageSize: number }
export type ProjectFilters = { search?: string; isActive?: boolean; page: number; pageSize: number }
export type TypeInput = { code: string; name: string; description?: string | null; payMultiplier: number; isPaid: boolean }
export type ProjectInput = { code: string; name: string; description?: string | null }
export type SettingsInput = Omit<OvertimeSettings, 'id' | 'rowVersion'> & { rowVersion: string }
export type ApprovalSettingsInput = { isEnabled: boolean; requiredLevels: number; rowVersion: string }
export type ApprovalLevelInput = { levelNumber: number; name: string; approverType: ApproverType; approverRoleId?: string | null; approverEmployeeId?: string | null }
export type OvertimeRequestStatus = 1 | 2 | 3 | 4
export type OvertimeDayCategory = 1 | 2 | 3
export type OvertimeSegmentType = 1 | 2 | 3
export type OvertimeApprovalStatus = 1 | 2 | 3 | 4
export type OvertimeRequestInput = { overtimeTypeId: string; projectId?: string | null; parentOvertimeRequestId?: string | null; segmentType: OvertimeSegmentType; startDate: string; endDate: string; startTime: string; endTime: string; reason: string; workDescription?: string | null }
export type OvertimeUpdateRequest = OvertimeRequestInput & { rowVersion: string }
export type OvertimeCancelInput = { cancellationReason?: string | null; rowVersion: string }
export type OvertimeDecisionInput = { comment?: string | null; rowVersion: string; approvalRowVersion?: string | null }
export type OvertimeRequestFilters = { status?: OvertimeRequestStatus; startDate?: string; endDate?: string; overtimeTypeId?: string; projectId?: string; page: number; pageSize: number }
export type OvertimeApprovalFilters = OvertimeRequestFilters & { employeeId?: string; departmentId?: string; fromDate?: string; toDate?: string; search?: string; pageNumber?: number }
export type OvertimeRequestParentOption = { id: string; requestNumber: string | null; startDate: string; endDate?: string; startTime: string; endTime: string; projectId: string | null; projectNameSnapshot: string | null }
export type OvertimeRequestOptions = { types: OvertimeTypeOption[]; projects: OvertimeProjectOption[]; settings: OvertimeSettings; companyTimeZone: string; eligibleParents: OvertimeRequestParentOption[]; segmentTypes: OvertimeSegmentType[]; canRequest: boolean; blockingReason: string | null }
export type OvertimeCalculation = { isValid: boolean; blockingReason: string | null; dayCategory: OvertimeDayCategory | null; startDate: string; endDate: string; startTime: string; endTime: string; startDateTimeUtc: string | null; endDateTimeUtc: string | null; requestedMinutes: number; durationText: string; type: OvertimeTypeOption | null; project: OvertimeProjectOption | null; maxMinutesPerRequest: number; maxMinutesPerWorkDate: number; minimumRequestMinutes: number; existingMinutes: number; remainingMinutes: number }
export type OvertimeRequestListItem = { id: string; requestNumber: string | null; type: OvertimeTypeOption; projectNameSnapshot: string | null; dayCategory: OvertimeDayCategory; segmentType: OvertimeSegmentType; startDate: string; endDate: string; startTime: string; endTime: string; requestedMinutes: number; approvedMinutes: number | null; status: OvertimeRequestStatus; currentApprovalLevel: number | null; submittedAtUtc: string; canEdit: boolean; canCancel: boolean; overtimeRequestId: string; overtimeTypeId: string; projectId: string | null; parentOvertimeRequestId: string | null; employeeId: string | null; employeeCode: string | null; employeeFullName: string | null; departmentId: string | null; departmentName: string | null; rowVersion: string }
export type OvertimeApprovalTimelineItem = { id: string; levelNumber: number; approverType: ApproverType; approverUserId: string | null; approverRoleId: string | null; status: OvertimeApprovalStatus; comment: string | null; actedAtUtc: string | null; rowVersion: string }
export type OvertimeRequestDetails = { request: OvertimeRequestListItem; reason: string; workDescription: string | null; cancellationReason: string | null; parent: OvertimeRequestListItem | null; continuations: OvertimeRequestListItem[]; approvals: OvertimeApprovalTimelineItem[]; canEdit: boolean; canCancel: boolean; canApprove: boolean; canDecline: boolean }
export type OvertimeApprovalQueueEmployeeOption = { id: string; employeeCode: string; fullName: string; departmentId: string | null; departmentName: string | null }
export type OvertimeApprovalQueueDepartmentOption = { id: string; code: string; name: string }
export type OvertimeApprovalQueueOptions = { employees: OvertimeApprovalQueueEmployeeOption[]; departments: OvertimeApprovalQueueDepartmentOption[]; statuses: OvertimeRequestStatus[] }
export type OvertimeCompanyFilters = { search?: string; employeeId?: string; departmentId?: string; status?: OvertimeRequestStatus; overtimeTypeId?: string; projectId?: string; dayCategory?: OvertimeDayCategory; segmentType?: OvertimeSegmentType; fromDate?: string; toDate?: string; page: number; pageSize: number }
export type OvertimeCompanyOptions = { employees: OvertimeApprovalQueueEmployeeOption[]; departments: OvertimeApprovalQueueDepartmentOption[]; types: OvertimeTypeOption[]; projects: OvertimeProjectOption[]; statuses: OvertimeRequestStatus[]; dayCategories: OvertimeDayCategory[]; segmentTypes: OvertimeSegmentType[] }
export type OvertimeDashboardSummary = { startDate: string | null; endDate: string | null; pendingCount: number; pendingMinutes: number; approvedCount: number; approvedMinutes: number; declinedCount: number; cancelledCount: number; workingDayApprovedMinutes: number; restDayApprovedMinutes: number; holidayApprovedMinutes: number }
