import { AlertCircle, LocateFixed, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Button } from '../../../components/ui/Button'
import { useAttendanceEmployeeMutations } from '../hooks/useAttendanceEmployee'
import { useCurrentPosition } from '../hooks/useCurrentPosition'
import type { AttendanceRecord, CheckInOptions } from '../types/attendance.types'
import { formatLocal, formatUtc } from '../utils/attendanceFormatters'

export function AttendanceActionDialog({ mode, options, record, timeZone, onClose }: { mode: 'check-in' | 'check-out'; options: CheckInOptions; record?: AttendanceRecord | null; timeZone?: string; onClose: () => void }) {
  const position = useCurrentPosition(); const mutations = useAttendanceEmployeeMutations(); const [remark, setRemark] = useState(''); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [showReason, setShowReason] = useState(options.settings.requireOutsideLocationReason && options.settings.allowOutsideLocation)
  const busy = mutations.checkIn.isPending || mutations.checkOut.isPending
  const resetPosition = position.reset
  useEffect(() => () => resetPosition(), [resetPosition])
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); if (options.settings.requireLocation && !position.position) { setError('Use Current Location before submitting.'); return } if (mode === 'check-in' && options.settings.requireCheckInRemark && !remark.trim()) { setError('A check-in remark is required.'); return } if (mode === 'check-out' && options.settings.requireCheckOutRemark && !remark.trim()) { setError('A check-out remark is required.'); return } try { if (mode === 'check-in') await mutations.checkIn.mutateAsync({ latitude: position.position?.latitude ?? null, longitude: position.position?.longitude ?? null, remark: remark.trim() || null, outsideLocationReason: reason.trim() || null }); else if (record) await mutations.checkOut.mutateAsync({ id: record.id, request: { latitude: position.position?.latitude ?? null, longitude: position.position?.longitude ?? null, remark: remark.trim() || null, outsideLocationReason: reason.trim() || null, rowVersion: record.rowVersion } }); onClose() } catch (value) { const message = (value as Error).message || 'The Attendance action could not be completed.'; setError(message); if (/outside|reason/i.test(message)) setShowReason(true) } }
  const scheduled = mode === 'check-in' ? options.scheduledStartDateTimeLocal : options.scheduledEndDateTimeLocal
  const locationMessage = position.state === 'requesting' ? 'Requesting a fresh browser location…' : position.state === 'success' ? 'Location captured. The server will determine the approved radius.' : position.state === 'denied' ? 'Location permission was denied. Allow access in your browser or continue without location if it is optional.' : position.state === 'timeout' ? 'The location request timed out. Try again.' : position.state === 'unavailable' ? 'Your position is unavailable. Try again or check device location services.' : position.state === 'unsupported' ? 'Location is unavailable in this browser or context.' : options.settings.requireLocation ? 'Location is required for this attendance action.' : 'Location is optional. You can capture it for this event.'
  return <div className="dialog-backdrop"><section className="dialog-panel attendance-action-dialog" role="dialog" aria-modal="true" aria-labelledby="attendance-action-title" aria-describedby="attendance-action-description"><header className="dialog-header"><div><h2 id="attendance-action-title">{mode === 'check-in' ? 'Check In' : 'Check Out'}</h2><p id="attendance-action-description">The server records the official time. This page only collects your optional event details.</p></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close Attendance dialog"><X size={18} /></button></header><form className="attendance-action-form" onSubmit={(event) => void submit(event)}><div className="attendance-action-context"><strong>{options.resolvedShift?.code} · {options.resolvedShift?.name || 'Current shift'}</strong><span>Scheduled {mode === 'check-in' ? 'start' : 'end'}: {formatLocal(scheduled)}</span>{mode === 'check-out' && record?.checkInDateTimeUtc && <span>Checked in: {formatUtc(record.checkInDateTimeUtc, timeZone)}</span>}</div>{error && <div className="alert alert-error" role="alert"><AlertCircle size={16} aria-hidden="true" />{error}</div>}<div className="attendance-location-request"><div><strong>Location</strong><p>{locationMessage}</p></div><Button type="button" variant="secondary" onClick={position.request} disabled={busy || position.state === 'requesting'}><LocateFixed size={16} />{position.state === 'requesting' ? 'Locating…' : position.state === 'success' ? 'Refresh location' : 'Use Current Location'}</Button></div>{position.position && <p className="attendance-captured" role="status">Location captured ({position.position.latitude.toFixed(4)}, {position.position.longitude.toFixed(4)})</p>}<div className="attendance-dialog-fields"><label className="attendance-dialog-field"><span>Remark{((mode === 'check-in' && options.settings.requireCheckInRemark) || (mode === 'check-out' && options.settings.requireCheckOutRemark)) && <i>*</i>}</span><textarea value={remark} onChange={(event) => setRemark(event.target.value)} maxLength={1000} rows={3} placeholder="Add context if needed" /></label>{showReason && <label className="attendance-dialog-field"><span>Outside-location reason</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} maxLength={1000} rows={3} placeholder="Explain why you are outside an approved location" /></label>}</div><div className="dialog-actions"><Button type="button" variant="secondary" onClick={onClose} disabled={busy}>Cancel</Button><Button type="submit" disabled={busy || (options.settings.requireLocation && !position.position)}>{busy ? 'Submitting…' : mode === 'check-in' ? 'Check In' : 'Check Out'}</Button></div></form></section></div>
}
