import { AlertTriangle, ChevronLeft, ChevronRight, Clock3, MapPin, Settings2 } from 'lucide-react'
import { NavLink, useLocation } from 'react-router-dom'
import { Button } from '../../../components/ui/Button'
import { Card, CardContent } from '../../../components/ui/Card'
import { PageHeader } from '../../../components/common/PageHeader'
import { cn } from '../../../lib/utils'
import { PermissionGuard } from '../../auth/components/PermissionGuard'
import { Permissions } from '../../../lib/permissions'

export function AttendanceNavigation() {
  const location = useLocation()
  if (location.pathname === '/dashboard' || location.pathname === '/dashboard/attendance' || location.pathname.startsWith('/dashboard/attendance/')) return null
  return <nav className="attendance-subnav" aria-label="Attendance configuration"><NavLink to="/attendance/shifts">Work Shifts</NavLink><NavLink to="/attendance/locations">Locations</NavLink><NavLink to="/attendance/assignments">Shift Assignments</NavLink><NavLink to="/attendance/settings">Attendance Settings</NavLink></nav>
}

export function EmployeeAttendanceNavigation() { return <><nav className="attendance-subnav" aria-label="My Attendance"><NavLink to="/attendance">Today</NavLink><NavLink to="/attendance/history">My History</NavLink></nav><PermissionGuard permission={Permissions.Attendance.Manage}><AttendanceNavigation /></PermissionGuard></> }

export function AttendancePageHeader({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) {
  return <><PageHeader eyebrow="Attendance / Configuration" title={title} description={description} action={action} /><AttendanceNavigation /></>
}

export function StatusBadge({ active, label }: { active: boolean; label?: string }) { return <span className={cn('badge attendance-status', active ? 'attendance-status-active' : 'attendance-status-inactive')}>{label ?? (active ? 'Active' : 'Inactive')}</span> }
export function DefaultBadge() { return <span className="badge attendance-default">Default</span> }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="empty-state attendance-empty"><div className="empty-icon"><Settings2 size={20} aria-hidden="true" /></div><h2>{title}</h2><p>{description}</p>{action && <div className="attendance-empty-action">{action}</div>}</div> }
export function ErrorState({ title, error, retry }: { title: string; error?: unknown; retry: () => void }) { const status = (error as { status?: number } | undefined)?.status; return <div className="inline-error" role="alert"><AlertTriangle size={22} aria-hidden="true" /><h2>{title}</h2><p>{status === 403 ? 'You do not have permission to manage Attendance configuration.' : (error as Error | undefined)?.message ?? 'Check your connection and try again.'}</p><Button variant="secondary" onClick={retry}>Retry</Button></div> }
export function LoadingState({ label = 'Loading Attendance configuration…' }: { label?: string }) { return <div className="attendance-loading" role="status" aria-label={label}><span /><span /><span /><span /></div> }
export function Pagination({ page, totalPages, totalCount, pageSize, onPage, onPageSize }: { page: number; totalPages: number; totalCount: number; pageSize: number; onPage: (page: number) => void; onPageSize: (size: number) => void }) { return <div className="pagination attendance-pagination"><span>{totalCount} result{totalCount === 1 ? '' : 's'}</span><label>Rows <select value={pageSize} onChange={(event) => onPageSize(Number(event.target.value))}><option value="10">10</option><option value="20">20</option><option value="50">50</option></select></label><div><Button variant="ghost" size="sm" disabled={page <= 1} onClick={() => onPage(page - 1)}><ChevronLeft size={15} /> Previous</Button><span>Page {page} of {Math.max(1, totalPages)}</span><Button variant="ghost" size="sm" disabled={page >= totalPages} onClick={() => onPage(page + 1)}>Next <ChevronRight size={15} /></Button></div></div> }
export function ConfirmDialog({ title, message, confirmLabel = 'Confirm', busy, onConfirm, onClose }: { title: string; message: string; confirmLabel?: string; busy?: boolean; onConfirm: () => void; onClose: () => void }) { return <div className="dialog-backdrop"><section className="dialog-panel attendance-confirm" role="dialog" aria-modal="true" aria-labelledby="attendance-confirm-title"><header className="dialog-header"><div><h2 id="attendance-confirm-title">{title}</h2><p>{message}</p></div></header><div className="confirm-copy"><Clock3 size={18} aria-hidden="true" /> This changes the configuration state without deleting historical records.</div><div className="dialog-actions"><Button variant="secondary" onClick={onClose} disabled={busy}>Cancel</Button><Button onClick={onConfirm} disabled={busy}>{busy ? 'Working…' : confirmLabel}</Button></div></section></div> }
export function Field({ label, value, onChange, error, required, type = 'text', min, max, step, placeholder, disabled }: { label: string; value: string | number; onChange: (value: string) => void; error?: string; required?: boolean; type?: string; min?: number; max?: number; step?: string; placeholder?: string; disabled?: boolean }) { const id = `attendance-${label.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`; return <div className="attendance-field"><label htmlFor={id}>{label}{required && <span className="required-mark">*</span>}</label><input id={id} type={type} value={value} onChange={(event) => onChange(event.target.value)} min={min} max={max} step={step} placeholder={placeholder} disabled={disabled} aria-invalid={Boolean(error)} />{error && <p className="field-error" role="alert">{error}</p>}</div> }
export function TextAreaField({ label, value, onChange, error }: { label: string; value: string; onChange: (value: string) => void; error?: string }) { const id = `attendance-${label.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`; return <div className="attendance-field attendance-field-wide"><label htmlFor={id}>{label}</label><textarea id={id} value={value} onChange={(event) => onChange(event.target.value)} rows={3} aria-invalid={Boolean(error)} />{error && <p className="field-error" role="alert">{error}</p>}</div> }
export function Toggle({ label, description, checked, onChange, disabled }: { label: string; description?: string; checked: boolean; onChange: (value: boolean) => void; disabled?: boolean }) { return <label className={cn('attendance-toggle', disabled && 'attendance-toggle-disabled')}><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} disabled={disabled} /><span><strong>{label}</strong>{description && <small>{description}</small>}</span></label> }
export function SelectField({ label, value, onChange, children, error, required, disabled }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode; error?: string; required?: boolean; disabled?: boolean }) { const id = `attendance-${label.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`; return <div className="attendance-field"><label htmlFor={id}>{label}{required && <span className="required-mark">*</span>}</label><select id={id} value={value} onChange={(event) => onChange(event.target.value)} disabled={disabled} aria-invalid={Boolean(error)}>{children}</select>{error && <p className="field-error" role="alert">{error}</p>}</div> }
export function DateField({ label, value, onChange, error, required }: { label: string; value: string; onChange: (value: string) => void; error?: string; required?: boolean }) { return <Field label={label} value={value} onChange={onChange} error={error} required={required} type="date" /> }
export function FormError({ message }: { message?: string }) { return message ? <div className="alert alert-error attendance-form-error" role="alert">{message}</div> : null }
export function FormSurface({ children }: { children: React.ReactNode }) { return <Card className="attendance-form-surface"><CardContent>{children}</CardContent></Card> }
export function LocationHint() { return <p className="attendance-helper"><MapPin size={14} aria-hidden="true" /> Use decimal GPS coordinates, for example 16.8409 and 96.1735.</p> }
