import { zodResolver } from '@hookform/resolvers/zod'
import { X } from 'lucide-react'
import { useForm } from 'react-hook-form'
import { useState } from 'react'
import { useLeaveMutations } from '../hooks/useLeave'
import { leaveBalanceSchema, type LeaveBalanceFormValues } from '../schemas/leaveSchemas'
import type { LeaveBalance, LeaveType } from '../types/leave.types'
import type { Employee } from '../../employees/types/employee.types'
import { useEmployees } from '../../employees/hooks/useEmployees'
import { Button } from '../../../components/ui/Button'
import { Alert } from '../../../components/ui/Alert'
import { toast } from 'sonner'
import type { ApiError } from '../../../lib/api/apiError'

export function LeaveBalanceFormDialog({ balance, employees: initialEmployees, types, onClose }: { balance?: LeaveBalance; employees: Employee[]; types: LeaveType[]; onClose: () => void }) { const { assignBalance, updateBalance } = useLeaveMutations(); const [employeeSearch, setEmployeeSearch] = useState(''); const employeeQuery = useEmployees({ page: 1, pageSize: 100, search: employeeSearch || undefined, includeInactive: false, sortBy: 'EmployeeCode', sortDirection: 'asc' }); const employees = employeeQuery.data?.items ?? initialEmployees; const form = useForm<LeaveBalanceFormValues>({ resolver: zodResolver(leaveBalanceSchema), mode: 'onBlur', defaultValues: balance ? { employeeId: balance.employee.id, leaveTypeId: balance.leaveType.id, balanceYear: balance.balanceYear, entitledDays: balance.entitledDays, carriedForwardDays: balance.carriedForwardDays, adjustedDays: balance.adjustedDays } : { employeeId: '', leaveTypeId: '', balanceYear: new Date().getFullYear(), entitledDays: 0, carriedForwardDays: 0, adjustedDays: 0 } }); const pending = form.formState.isSubmitting; async function submit(values: LeaveBalanceFormValues) { form.clearErrors('root'); try { if (balance) await updateBalance.mutateAsync({ id: balance.id, request: { entitledDays: values.entitledDays, carriedForwardDays: values.carriedForwardDays, adjustedDays: values.adjustedDays } }); else await assignBalance.mutateAsync(values); toast.success(balance ? 'Leave balance updated.' : 'Leave balance assigned.'); onClose() } catch (error) { const api = error as ApiError; form.setError('root', { type: 'server', message: api.status === 409 ? api.message || 'This balance conflicts with an existing allocation or policy.' : 'The balance could not be saved.' }) } }
 const error = form.formState.errors.root?.message; return <div className="dialog-backdrop"><section className="dialog-panel leave-dialog" role="dialog" aria-modal="true" aria-labelledby="balance-dialog-title"><header className="dialog-header"><div><h2 id="balance-dialog-title">{balance ? 'Update employee balance' : 'Assign employee balance'}</h2><p>{balance ? 'Used and pending days are controlled by Leave workflows.' : 'Create a yearly allocation for an employee.'}</p></div><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={18} /></button></header><form className="leave-form" onSubmit={(event) => void form.handleSubmit(submit)(event)} noValidate>{error && <Alert className="form-alert">{error}</Alert>}{balance ? <div className="balance-context"><strong>{balance.employee.fullName}</strong><span>{balance.employee.employeeCode} · {balance.leaveType.name} · {balance.balanceYear}</span><span>Used {balance.usedDays} · Pending {balance.pendingDays} · Available {balance.availableDays}</span></div> : <><label className="form-field"><span>Search employees</span><input value={employeeSearch} onChange={(event) => setEmployeeSearch(event.target.value)} placeholder="Search code or name" /></label><SelectField label="Employee" name="employeeId" form={form} options={employees.filter((employee) => employee.isActive).map((employee) => ({ value: employee.id, label: `${employee.employeeCode} · ${employee.fullName}${employee.department ? ` · ${employee.department.name}` : ''}` }))} placeholder={employeeQuery.isFetching ? 'Searching…' : 'Select employee'} /><SelectField label="Leave Type" name="leaveTypeId" form={form} options={types.filter((type) => type.isActive).map((type) => ({ value: type.id, label: `${type.code} · ${type.name}` }))} placeholder="Select Leave Type" /><NumberField label="Balance year" name="balanceYear" form={form} min={2000} max={2100} /></>}<NumberField label="Entitled days" name="entitledDays" form={form} min={0} max={366} step={0.01} /><NumberField label="Carried forward days" name="carriedForwardDays" form={form} min={0} max={366} step={0.01} /><NumberField label="Adjusted days" name="adjustedDays" form={form} min={-366} max={366} step={0.01} /><div className="dialog-actions"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={pending}>{pending ? 'Saving…' : balance ? 'Save changes' : 'Assign balance'}</Button></div></form></section></div> }
function NumberField({ label, name, form, min, max, step = 0.01 }: { label: string; name: keyof LeaveBalanceFormValues; form: ReturnType<typeof useForm<LeaveBalanceFormValues>>; min: number; max: number; step?: number }) { const error = form.formState.errors[name]?.message as string | undefined; const id = `balance-${String(name)}`; return <div className="form-field"><label htmlFor={id}>{label}</label><input id={id} type="number" min={min} max={max} step={step} {...form.register(name, { valueAsNumber: true })} />{error && <p className="field-error" role="alert">{error}</p>}</div> }
function SelectField({ label, name, form, options, placeholder }: { label: string; name: 'employeeId' | 'leaveTypeId'; form: ReturnType<typeof useForm<LeaveBalanceFormValues>>; options: { value: string; label: string }[]; placeholder: string }) { const error = form.formState.errors[name]?.message as string | undefined; const id = `balance-${name}`; return <div className="form-field"><label htmlFor={id}>{label}</label><select id={id} {...form.register(name)}><option value="">{placeholder}</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>{error && <p className="field-error" role="alert">{error}</p>}</div> }
