import { zodResolver } from '@hookform/resolvers/zod'
import { X } from 'lucide-react'
import { useForm } from 'react-hook-form'
import { useLeaveMutations } from '../hooks/useLeave'
import { leaveTypeSchema, type LeaveTypeFormValues } from '../schemas/leaveSchemas'
import type { LeaveType } from '../types/leave.types'
import { Button } from '../../../components/ui/Button'
import { Alert } from '../../../components/ui/Alert'
import type { ApiError } from '../../../lib/api/apiError'
import { toast } from 'sonner'
import { useEffect, useRef } from 'react'

export function LeaveTypeFormDialog({ type, onClose }: { type?: LeaveType; onClose: () => void }) {
  const { addType, updateType } = useLeaveMutations(); const form = useForm<LeaveTypeFormValues>({ resolver: zodResolver(leaveTypeSchema), mode: 'onBlur', defaultValues: type ? { ...type, description: type.description ?? '' } : { code: '', name: '', description: '', defaultDaysPerYear: 0, isPaid: true, allowHalfDay: true, allowNegativeBalance: false, requiresAttachment: false, isActive: true } }); const panel = useRef<HTMLElement>(null)
  useEffect(() => { panel.current?.querySelector<HTMLElement>('input')?.focus(); const close = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close) }, [onClose])
  async function submit(values: LeaveTypeFormValues) { form.clearErrors('root'); const request = { ...values, code: values.code.trim().toUpperCase(), name: values.name.trim(), description: values.description.trim() || null }; try { if (type) await updateType.mutateAsync({ id: type.id, request }); else await addType.mutateAsync(request); toast.success(type ? 'Leave Type updated.' : 'Leave Type added.'); onClose() } catch (error) { const api = error as ApiError; form.setError('root', { type: 'server', message: api.status === 409 ? api.message || 'A Leave Type with this code or name already exists.' : api.status === 403 ? 'You do not have permission to manage Leave Types.' : 'The Leave Type could not be saved.' }) } }
  const error = form.formState.errors.root?.message; const pending = form.formState.isSubmitting
  return <div className="dialog-backdrop"><section ref={panel} className="dialog-panel leave-dialog" role="dialog" aria-modal="true" aria-labelledby="leave-type-dialog-title"><header className="dialog-header"><div><h2 id="leave-type-dialog-title">{type ? 'Edit Leave Type' : 'Add Leave Type'}</h2><p>Configure the category and balance policy used by your company.</p></div><button className="icon-button" type="button" onClick={onClose} aria-label="Close dialog"><X size={18} /></button></header><form className="leave-form" onSubmit={(event) => void form.handleSubmit(submit)(event)} noValidate>{error && <Alert className="form-alert">{error}</Alert>}<Field label="Code" name="code" form={form} required /><Field label="Name" name="name" form={form} required /><Field label="Description" name="description" form={form} textarea /><Field label="Default days per year" name="defaultDaysPerYear" form={form} type="number" step="0.01" required /><div className="leave-toggle-grid"><Toggle label="Paid Leave" name="isPaid" form={form} /><Toggle label="Allow half day" name="allowHalfDay" form={form} /><Toggle label="Allow negative balance" name="allowNegativeBalance" form={form} /><Toggle label="Requires attachment" name="requiresAttachment" form={form} />{type && <Toggle label="Active" name="isActive" form={form} />}</div><div className="dialog-actions"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={pending}>{pending ? 'Saving…' : type ? 'Save changes' : 'Add Leave Type'}</Button></div></form></section></div>
}
function Field({ label, name, form, type = 'text', step, textarea = false, required = false }: { label: string; name: keyof LeaveTypeFormValues; form: ReturnType<typeof useForm<LeaveTypeFormValues>>; type?: string; step?: string; textarea?: boolean; required?: boolean }) { const id = `leave-${String(name)}`; const error = form.formState.errors[name]?.message as string | undefined; const props = { id, 'aria-invalid': Boolean(error), 'aria-describedby': error ? `${id}-error` : undefined }; return <div className="form-field"><label htmlFor={id}>{label}{required && <span className="required-mark">*</span>}</label>{textarea ? <textarea {...props} rows={3} {...form.register(name)} /> : <input {...props} type={type} step={step} {...form.register(name, type === 'number' ? { valueAsNumber: true } : undefined)} />} {error && <p id={`${id}-error`} className="field-error" role="alert">{error}</p>}</div> }
function Toggle({ label, name, form }: { label: string; name: keyof LeaveTypeFormValues; form: ReturnType<typeof useForm<LeaveTypeFormValues>> }) { return <label className="switch-field"><input type="checkbox" {...form.register(name)} /><span>{label}</span></label> }
