import { keepPreviousData, useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { addLeaveType, deactivateLeaveType, getLeaveType, getLeaveTypes, updateLeaveType } from '../api/leaveTypeApi'
import { assignLeaveBalance, getEmployeeLeaveBalances, getLeaveBalances, updateLeaveBalance } from '../api/leaveBalanceApi'
import { getApprovalLevels, getApprovalSetting, getConfigurationOptions, updateApprovalLevels, updateApprovalSetting } from '../api/leaveSettingApi'
import { leaveKeys } from '../api/leaveKeys'
import type { LeaveBalanceListParams, LeaveTypeListParams } from '../types/leave.types'
export function useLeaveTypes(params: LeaveTypeListParams) { return useQuery({ queryKey: leaveKeys.typeList(params), queryFn: ({ signal }) => getLeaveTypes(params, signal), placeholderData: keepPreviousData }) }
export function useLeaveType(id: string | null) { return useQuery({ queryKey: leaveKeys.typeDetail(id ?? ''), queryFn: ({ signal }) => getLeaveType(id as string, signal), enabled: Boolean(id) }) }
export function useLeaveBalances(params: LeaveBalanceListParams) { return useQuery({ queryKey: leaveKeys.balanceList(params), queryFn: ({ signal }) => getLeaveBalances(params, signal), placeholderData: keepPreviousData }) }
export function useEmployeeLeaveBalances(id: string | null, year?: number) { return useQuery({ queryKey: leaveKeys.employeeBalances(id ?? '', year), queryFn: ({ signal }) => getEmployeeLeaveBalances(id as string, year, signal), enabled: Boolean(id) }) }
export function useLeaveApprovalConfiguration() { const setting = useQuery({ queryKey: leaveKeys.approvalSetting(), queryFn: ({ signal }) => getApprovalSetting(signal) }); const levels = useQuery({ queryKey: leaveKeys.approvalLevels(), queryFn: ({ signal }) => getApprovalLevels(signal) }); const options = useQuery({ queryKey: leaveKeys.configurationOptions(), queryFn: ({ signal }) => getConfigurationOptions(signal), staleTime: 5 * 60 * 1000 }); return { setting, levels, options } }
export function useLeaveMutations() { const client = useQueryClient(); const invalidate = () => { void client.invalidateQueries({ queryKey: leaveKeys.types() }); void client.invalidateQueries({ queryKey: leaveKeys.balances() }) }; return { addType: useMutation({ mutationFn: addLeaveType, onSuccess: invalidate }), updateType: useMutation({ mutationFn: ({ id, request }: { id: string; request: Parameters<typeof updateLeaveType>[1] }) => updateLeaveType(id, request), onSuccess: invalidate }), deactivateType: useMutation({ mutationFn: deactivateLeaveType, onSuccess: invalidate }), assignBalance: useMutation({ mutationFn: assignLeaveBalance, onSuccess: invalidate }), updateBalance: useMutation({ mutationFn: ({ id, request }: { id: string; request: Parameters<typeof updateLeaveBalance>[1] }) => updateLeaveBalance(id, request), onSuccess: invalidate }), updateSetting: useMutation({ mutationFn: updateApprovalSetting, onSuccess: () => void client.invalidateQueries({ queryKey: leaveKeys.approvalSetting() }) }), updateLevels: useMutation({ mutationFn: updateApprovalLevels, onSuccess: () => void client.invalidateQueries({ queryKey: leaveKeys.approvalLevels() }) }) } }
