import { apiClient } from '../../../lib/api/apiClient'
import type { ApprovalLevel, ApprovalOptions, ApprovalSettingsInput, OvertimeApprovalQueueOptions, OvertimeApprovalSettings, OvertimeProject, OvertimeSettings, OvertimeSettingsOptions, OvertimeType, PagedResponse, ProjectFilters, ProjectInput, SettingsInput, TypeFilters, TypeInput, ApprovalLevelInput, OvertimeCalculation, OvertimeCancelInput, OvertimeDecisionInput, OvertimeApprovalFilters, OvertimeRequestDetails, OvertimeRequestFilters, OvertimeRequestInput, OvertimeRequestOptions, OvertimeRequestListItem, OvertimeUpdateRequest, OvertimeCompanyFilters, OvertimeCompanyOptions, OvertimeDashboardSummary } from '../types/overtime.types'
const id = (value: string) => encodeURIComponent(value)
export async function getOvertimeTypes(params: TypeFilters, signal?: AbortSignal) { return (await apiClient.get<PagedResponse<OvertimeType>>('/api/OvertimeType/GetOvertimeTypes', { params, signal })).data }
export async function getOvertimeType(value: string, signal?: AbortSignal) { return (await apiClient.get<OvertimeType>(`/api/OvertimeType/GetOvertimeTypeById/${id(value)}`, { signal })).data }
export async function getOvertimeTypeOptions(signal?: AbortSignal) { return (await apiClient.get<{ paidOptions: boolean[] }>('/api/OvertimeType/GetOvertimeTypeFormOptions', { signal })).data }
export async function addOvertimeType(request: TypeInput) { return (await apiClient.post<OvertimeType>('/api/OvertimeType/AddOvertimeType', request)).data }
export async function updateOvertimeType(value: string, request: TypeInput & { isActive: boolean; rowVersion: string }) { const body = { ...request } as typeof request & { id?: string }; delete body.id; return (await apiClient.put<OvertimeType>(`/api/OvertimeType/UpdateOvertimeType/${id(value)}`, body)).data }
export async function activateOvertimeType(value: string) { return (await apiClient.post<OvertimeType>(`/api/OvertimeType/ActivateOvertimeType/${id(value)}`)).data }
export async function deactivateOvertimeType(value: string) { await apiClient.post<void>(`/api/OvertimeType/DeactivateOvertimeType/${id(value)}`) }
export async function getOvertimeProjects(params: ProjectFilters, signal?: AbortSignal) { return (await apiClient.get<PagedResponse<OvertimeProject>>('/api/OvertimeProject/GetOvertimeProjects', { params, signal })).data }
export async function getOvertimeProject(value: string, signal?: AbortSignal) { return (await apiClient.get<OvertimeProject>(`/api/OvertimeProject/GetOvertimeProjectById/${id(value)}`, { signal })).data }
export async function addOvertimeProject(request: ProjectInput) { return (await apiClient.post<OvertimeProject>('/api/OvertimeProject/AddOvertimeProject', request)).data }
export async function updateOvertimeProject(value: string, request: ProjectInput & { isActive: boolean; rowVersion: string }) { const body = { ...request } as typeof request & { id?: string }; delete body.id; return (await apiClient.put<OvertimeProject>(`/api/OvertimeProject/UpdateOvertimeProject/${id(value)}`, body)).data }
export async function activateOvertimeProject(value: string) { return (await apiClient.post<OvertimeProject>(`/api/OvertimeProject/ActivateOvertimeProject/${id(value)}`)).data }
export async function deactivateOvertimeProject(value: string) { await apiClient.post<void>(`/api/OvertimeProject/DeactivateOvertimeProject/${id(value)}`) }
export async function getOvertimeSettings(signal?: AbortSignal) { return (await apiClient.get<OvertimeSettings>('/api/OvertimeSetting/GetOvertimeSettings', { signal })).data }
export async function getOvertimeSettingOptions(signal?: AbortSignal) { return (await apiClient.get<OvertimeSettingsOptions>('/api/OvertimeSetting/GetOvertimeSettingOptions', { signal })).data }
export async function updateOvertimeSettings(request: SettingsInput) { const body = { ...request } as SettingsInput & { id?: string }; delete body.id; return (await apiClient.put<OvertimeSettings>('/api/OvertimeSetting/UpdateOvertimeSettings', body)).data }
export async function getApprovalSettings(signal?: AbortSignal) { return (await apiClient.get<OvertimeApprovalSettings>('/api/OvertimeApproval/GetOvertimeApprovalSettings', { signal })).data }
export async function getApprovalOptions(signal?: AbortSignal) { return (await apiClient.get<ApprovalOptions>('/api/OvertimeApproval/GetOvertimeApprovalOptions', { signal })).data }
export async function updateApprovalSettings(request: ApprovalSettingsInput) { return (await apiClient.put<OvertimeApprovalSettings>('/api/OvertimeApproval/UpdateOvertimeApprovalSettings', request)).data }
export async function getApprovalLevels(signal?: AbortSignal) { return (await apiClient.get<ApprovalLevel[]>('/api/OvertimeApproval/GetOvertimeApprovalLevels', { signal })).data }
export async function getApprovalLevel(value: string, signal?: AbortSignal) { return (await apiClient.get<ApprovalLevel>(`/api/OvertimeApproval/GetOvertimeApprovalLevelById/${id(value)}`, { signal })).data }
export async function addApprovalLevel(request: ApprovalLevelInput) { return (await apiClient.post<ApprovalLevel>('/api/OvertimeApproval/AddOvertimeApprovalLevel', request)).data }
export async function updateApprovalLevel(value: string, request: ApprovalLevelInput & { isActive: boolean; rowVersion: string }) { return (await apiClient.put<ApprovalLevel>(`/api/OvertimeApproval/UpdateOvertimeApprovalLevel/${id(value)}`, request)).data }
export async function activateApprovalLevel(value: string) { return (await apiClient.post<ApprovalLevel>(`/api/OvertimeApproval/ActivateOvertimeApprovalLevel/${id(value)}`)).data }
export async function deactivateApprovalLevel(value: string) { await apiClient.post<void>(`/api/OvertimeApproval/DeactivateOvertimeApprovalLevel/${id(value)}`) }
export async function getOvertimeRequestOptions(signal?: AbortSignal) { return (await apiClient.get<OvertimeRequestOptions>('/api/OvertimeRequest/GetOvertimeRequestOptions', { signal })).data }
export async function calculateOvertimeRequest(request: OvertimeRequestInput) { return (await apiClient.post<OvertimeCalculation>('/api/OvertimeRequest/CalculateOvertimeRequest', request)).data }
export async function getMyOvertimeRequests(params: OvertimeRequestFilters, signal?: AbortSignal) { return (await apiClient.get<PagedResponse<OvertimeRequestListItem>>('/api/OvertimeRequest/GetMyOvertimeRequests', { params, signal })).data }
export async function getMyOvertimeRequest(value: string, signal?: AbortSignal) { return (await apiClient.get<OvertimeRequestDetails>(`/api/OvertimeRequest/GetOvertimeRequestById/${id(value)}`, { signal })).data }
export async function addOvertimeRequest(request: OvertimeRequestInput) { return (await apiClient.post<OvertimeRequestDetails>('/api/OvertimeRequest/AddOvertimeRequest', request)).data }
export async function updateOvertimeRequest(value: string, request: OvertimeUpdateRequest) { return (await apiClient.put<OvertimeRequestDetails>(`/api/OvertimeRequest/UpdateOvertimeRequest/${id(value)}`, request)).data }
export async function cancelOvertimeRequest(value: string, request: OvertimeCancelInput) { await apiClient.post<void>(`/api/OvertimeRequest/CancelOvertimeRequest/${id(value)}`, request) }
export async function getOvertimeApprovalQueue(params: OvertimeApprovalFilters, signal?: AbortSignal) { return (await apiClient.get<PagedResponse<OvertimeRequestListItem>>('/api/OvertimeRequest/GetOvertimeApprovalQueue', { params, signal })).data }
export async function getOvertimeApprovalQueueOptions(signal?: AbortSignal) { return (await apiClient.get<OvertimeApprovalQueueOptions>('/api/OvertimeApproval/GetOvertimeApprovalQueueOptions', { signal })).data }
export async function getOvertimeApprovalRequest(value: string, signal?: AbortSignal) { return (await apiClient.get<OvertimeRequestDetails>(`/api/OvertimeRequest/GetOvertimeApprovalRequestById/${id(value)}`, { signal })).data }
export async function approveOvertimeRequest(value: string, request: OvertimeDecisionInput) { return (await apiClient.post<OvertimeRequestDetails>(`/api/OvertimeRequest/ApproveOvertimeRequest/${id(value)}`, request)).data }
export async function declineOvertimeRequest(value: string, request: OvertimeDecisionInput) { return (await apiClient.post<OvertimeRequestDetails>(`/api/OvertimeRequest/DeclineOvertimeRequest/${id(value)}`, request)).data }
const monitoringParams = (params: Record<string, unknown>) => Object.fromEntries(Object.entries(params).filter(([, value]) => value !== undefined && value !== ''))
export async function getCompanyOvertime(params: OvertimeCompanyFilters, signal?: AbortSignal) { return (await apiClient.get<PagedResponse<OvertimeRequestListItem>>('/api/OvertimeRequest/GetCompanyOvertimeRequests', { params: monitoringParams(params), signal })).data }
export async function getCompanyOvertimeById(value: string, signal?: AbortSignal) { return (await apiClient.get<OvertimeRequestDetails>(`/api/OvertimeRequest/GetCompanyOvertimeRequestById/${id(value)}`, { signal })).data }
export async function getOvertimeDashboardSummary(params: Pick<OvertimeCompanyFilters, 'fromDate' | 'toDate'>, signal?: AbortSignal) { return (await apiClient.get<OvertimeDashboardSummary>('/api/OvertimeRequest/GetOvertimeDashboardSummary', { params: monitoringParams(params), signal })).data }
export async function getCompanyOvertimeOptions(signal?: AbortSignal) { return (await apiClient.get<OvertimeCompanyOptions>('/api/OvertimeRequest/GetCompanyOvertimeOptions', { signal })).data }
