export type LeaveApproverType = 1 | 2 | 3
export type LeaveType = { id: string; code: string; name: string; description: string | null; defaultDaysPerYear: number; isPaid: boolean; allowHalfDay: boolean; allowNegativeBalance: boolean; requiresAttachment: boolean; isActive: boolean; createdAtUtc: string; updatedAtUtc: string | null }
export type LeaveTypeForm = Omit<LeaveType, 'id' | 'createdAtUtc' | 'updatedAtUtc'>
export type LeaveTypeListParams = { search?: string; page: number; pageSize: number; includeInactive: boolean; isPaid?: boolean; allowHalfDay?: boolean; sortBy: 'Code' | 'Name' | 'CreatedAtUtc' | 'IsActive'; sortDirection: 'asc' | 'desc' }
export type EmployeeSummary = { id: string; employeeCode: string; fullName: string; jobTitle: string | null; isActive: boolean }
export type LeaveTypeSummary = { id: string; code: string; name: string; isActive: boolean; allowNegativeBalance: boolean }
export type LeaveBalance = { id: string; employee: EmployeeSummary; leaveType: LeaveTypeSummary; balanceYear: number; entitledDays: number; carriedForwardDays: number; adjustedDays: number; usedDays: number; pendingDays: number; totalAllocatedDays: number; availableDays: number; createdAtUtc: string; updatedAtUtc: string | null }
export type LeaveBalanceListParams = { search?: string; employeeId?: string; leaveTypeId?: string; departmentId?: string; balanceYear?: number; includeInactiveEmployees: boolean; page: number; pageSize: number; sortBy: 'Employee' | 'Year' | 'LeaveType'; sortDirection: 'asc' | 'desc' }
export type AddLeaveTypeRequest = Omit<LeaveTypeForm, 'isActive'>
export type UpdateLeaveTypeRequest = LeaveTypeForm
export type AssignLeaveBalanceRequest = { employeeId: string; leaveTypeId: string; balanceYear: number; entitledDays: number; carriedForwardDays: number; adjustedDays: number }
export type UpdateLeaveBalanceRequest = Pick<AssignLeaveBalanceRequest, 'entitledDays' | 'carriedForwardDays' | 'adjustedDays'>
export type LeaveApprovalSetting = { id: string; isEnabled: boolean; requiredLevels: number; allowPendingCancellation: boolean; createdAtUtc: string; updatedAtUtc: string | null }
export type UpdateLeaveApprovalSettingRequest = Omit<LeaveApprovalSetting, 'id' | 'createdAtUtc' | 'updatedAtUtc'>
export type LeaveApprovalLevel = { id: string; levelNumber: number; name: string; approverType: LeaveApproverType; approverRole: { id: string; name: string; normalizedName: string } | null; approverEmployee: { id: string; employeeCode: string; fullName: string; jobTitle: string | null; hasActiveLoginAccount: boolean } | null; isActive: boolean }
export type UpdateLeaveApprovalLevelRequest = { levelNumber: number; name: string; approverType: LeaveApproverType; approverRoleId: string | null; approverEmployeeId: string | null; isActive: boolean }
export type LeaveConfigurationOptions = { employees: { id: string; employeeCode: string; fullName: string; jobTitle: string | null; hasActiveLoginAccount: boolean }[]; roles: { id: string; name: string; normalizedName: string }[]; approverTypes: LeaveApproverType[]; requiredLevels: number[] }
export type PagedResponse<T> = { items: T[]; page: number; pageSize: number; totalCount: number; totalPages: number; hasPreviousPage: boolean; hasNextPage: boolean }
