import { Bell, ChevronRight, LoaderCircle, RefreshCw } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Button } from '../../../components/ui/Button'
import { Alert } from '../../../components/ui/Alert'
import { useNotificationList, useNotificationMutations, useNotificationUnreadCount } from '../hooks/useNotifications'
import { isSafeActionUrl } from '../utils/notificationFormatters'
import type { NotificationSummary } from '../types/notification.types'
import { NotificationItem } from './NotificationItem'
import { toast } from 'sonner'

export function NotificationBell() {
  const [open, setOpen] = useState(false); const wrapper = useRef<HTMLDivElement>(null); const button = useRef<HTMLButtonElement>(null); const navigate = useNavigate(); const count = useNotificationUnreadCount(); const list = useNotificationList({ pageNumber: 1, pageSize: 6 }); const mutations = useNotificationMutations(); const unread = count.data?.unreadCount ?? 0; const refetchCount = count.refetch; const refetchList = list.refetch
  useEffect(() => { if (!open) return; const close = (event: MouseEvent) => { if (wrapper.current && !wrapper.current.contains(event.target as Node)) setOpen(false) }; const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') { setOpen(false); button.current?.focus() } }; document.addEventListener('mousedown', close); document.addEventListener('keydown', escape); void refetchCount(); void refetchList(); return () => { document.removeEventListener('mousedown', close); document.removeEventListener('keydown', escape) } }, [open, refetchCount, refetchList])
  function openNotification(notification: NotificationSummary) { if (mutations.markRead.isPending || mutations.archive.isPending) return; if (!notification.isRead) mutations.markRead.mutate({ id: notification.id, request: { rowVersion: notification.rowVersion } }); setOpen(false); navigate(isSafeActionUrl(notification.actionUrl) ? notification.actionUrl : `/notifications?notification=${encodeURIComponent(notification.id)}`) }
  function markAll() { if (mutations.markAllRead.isPending) return; mutations.markAllRead.mutate(undefined, { onSuccess: () => toast.success('All notifications marked as read.'), onError: () => toast.error('Notifications could not be marked as read.') }) }
  return <div className="notification-bell-wrap" ref={wrapper}><button ref={button} type="button" className="icon-button notification-bell" aria-haspopup="dialog" aria-expanded={open} aria-label={`Notifications, ${unread} unread`} onClick={() => setOpen((value) => !value)}><Bell size={19} aria-hidden="true" />{unread > 0 && <span className="notification-count-badge" aria-label={`${unread} unread`}>{unread > 99 ? '99+' : unread}</span>}</button>{open && <section className="notification-popover" role="dialog" aria-label="Recent notifications"><header className="notification-popover-header"><div><strong>Notifications</strong><span>{unread ? `${unread} unread` : 'All caught up'}</span></div><Button type="button" variant="ghost" size="sm" onClick={markAll} disabled={mutations.markAllRead.isPending}>{mutations.markAllRead.isPending ? <LoaderCircle className="spin" size={14} /> : 'Mark all read'}</Button></header>{list.isPending ? <div className="notification-popover-state"><LoaderCircle className="spin" size={20} aria-hidden="true" />Loading notifications…</div> : list.isError ? <div className="notification-popover-state"><Alert role="alert">Notifications could not be loaded.</Alert><Button type="button" variant="secondary" size="sm" onClick={() => void list.refetch()}><RefreshCw size={14} /> Retry</Button></div> : list.data?.items.length ? <div className="notification-popover-list">{list.data.items.map((item) => <NotificationItem key={item.id} notification={item} onOpen={openNotification} />)}</div> : <div className="notification-popover-state"><Bell size={22} aria-hidden="true" /><strong>No notifications yet</strong><span>New workflow updates will appear here.</span></div>}<footer><Link to="/notifications" onClick={() => setOpen(false)}>View all notifications <ChevronRight size={15} aria-hidden="true" /></Link></footer></section>}</div>
}
