import { Bell, Mail, Smartphone } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Alert } from '../../../components/ui/Alert'
import { Button } from '../../../components/ui/Button'
import { Card, CardContent } from '../../../components/ui/Card'
import { useNotificationMutations, useNotificationPreferences } from '../hooks/useNotifications'
import type { NotificationModule, NotificationPreference, NotificationPreferenceUpdate } from '../types/notification.types'
import { eventLabel, moduleLabels } from '../utils/notificationFormatters'
import { toast } from 'sonner'

const events: Record<NotificationModule, string[]> = { System: ['SystemMessage'], Leave: ['LeaveRequestSubmitted', 'LeaveRequestApproved', 'LeaveRequestDeclined', 'LeaveRequestCancelled'], Attendance: ['AttendanceCorrectionSubmitted', 'AttendanceCorrectionApproved', 'AttendanceCorrectionDeclined', 'AttendanceCorrectionCancelled'], Overtime: ['OvertimeRequestSubmitted', 'OvertimeRequestApproved', 'OvertimeRequestDeclined', 'OvertimeRequestCancelled'] }

export function NotificationPreferencesPage() {
  const query = useNotificationPreferences(); const mutation = useNotificationMutations().updatePreference; const [saving, setSaving] = useState<string | null>(null)
  function value(module: NotificationModule, eventType: string): NotificationPreference | undefined { return query.data?.find((item) => item.module === module && item.eventType === eventType) }
  async function update(module: NotificationModule, eventType: string, channel: 'isInAppEnabled' | 'isEmailEnabled' | 'isPushEnabled', enabled: boolean) { const existing = value(module, eventType); const request: NotificationPreferenceUpdate = { module, eventType, isInAppEnabled: existing?.isInAppEnabled ?? true, isEmailEnabled: existing?.isEmailEnabled ?? false, isPushEnabled: existing?.isPushEnabled ?? false, ...(existing?.rowVersion ? { rowVersion: existing.rowVersion } : {}) }; request[channel] = enabled; setSaving(`${module}:${eventType}`); try { await mutation.mutateAsync(request); toast.success('Notification preference updated.') } catch (error) { toast.error((error as Error).message || 'The preference could not be updated.') } finally { setSaving(null) } }
  return <div className="notification-page"><header className="page-header"><div><p className="eyebrow">Settings</p><h1>Notification Preferences</h1><p className="page-description">Choose which in-app workflow updates you want to receive. Email and push delivery are not active yet.</p></div><Link className="button button-secondary button-md" to="/notifications"><Bell size={16} aria-hidden="true" /> Notification Center</Link></header>{query.isError ? <div className="notification-state" role="alert"><Alert>Preferences could not be loaded.</Alert><Button type="button" variant="secondary" onClick={() => void query.refetch()}>Retry</Button></div> : query.isPending ? <div className="notification-state" role="status">Loading preferences…</div> : <div className="preference-groups">{(Object.keys(events) as NotificationModule[]).map((module) => <Card key={module}><CardContent><div className="preference-group-heading"><div><p className="eyebrow">{moduleLabels[module]}</p><h2>{moduleLabels[module]} notifications</h2></div><span>Saved preferences override the application default.</span></div><div className="preference-table" role="table" aria-label={`${moduleLabels[module]} notification preferences`}><div className="preference-table-head" role="row"><span role="columnheader">Event</span><span role="columnheader"><Bell size={15} /> In-app</span><span role="columnheader"><Mail size={15} /> Email</span><span role="columnheader"><Smartphone size={15} /> Push</span></div>{events[module].map((eventType) => { const item = value(module, eventType); const key = `${module}:${eventType}`; return <div className="preference-row" role="row" key={eventType}><div><strong>{eventLabel(eventType)}</strong><span>In-app alerts are delivered immediately when available.</span></div><label className="switch-field"><span className="sr-only">Enable in-app for {eventLabel(eventType)}</span><input type="checkbox" checked={item?.isInAppEnabled ?? true} onChange={(event) => void update(module, eventType, 'isInAppEnabled', event.target.checked)} disabled={saving === key} /></label><label className="switch-field preference-unavailable"><span className="sr-only">Email delivery unavailable for {eventLabel(eventType)}</span><input type="checkbox" checked={false} disabled aria-describedby={`${key}-email-note`} /><span id={`${key}-email-note`} className="preference-coming-soon">Coming later</span></label><label className="switch-field preference-unavailable"><span className="sr-only">Push delivery unavailable for {eventLabel(eventType)}</span><input type="checkbox" checked={false} disabled aria-describedby={`${key}-push-note`} /><span id={`${key}-push-note`} className="preference-coming-soon">Coming later</span></label></div> })}</div></CardContent></Card>)}</div>}</div>
}
