import { useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Card, CardContent } from '../../../components/ui/Card'
import { PageHeader } from '../../../components/common/PageHeader'
import { LeaveNavigation } from '../components/LeaveNavigation'
import { LeaveRequestTable } from '../components/LeaveRequestTable'
import { useCompanyLeaveRequests } from '../hooks/useCompanyLeaveRequests'
import type { LeaveRequestFilters } from '../types/leaveRequest.types'
import { PermissionGuard } from '../../auth/components/PermissionGuard'
import { Permissions } from '../../../lib/permissions'
import { UnauthorizedPage } from '../../../pages/UnauthorizedPage'

export function CompanyLeaveRequestsPage() {
  const [url, setUrl] = useSearchParams(); const filters = useMemo<LeaveRequestFilters>(() => ({ search: url.get('search') || undefined, status: [1, 2, 3, 4].includes(Number(url.get('status'))) ? Number(url.get('status')) as LeaveRequestFilters['status'] : undefined, page: Math.max(1, Number(url.get('page')) || 1), pageSize: 10 }), [url]); const [search, setSearch] = useState(filters.search ?? ''); const query = useCompanyLeaveRequests(filters)
  const update = (change: Partial<LeaveRequestFilters>) => { const next = new URLSearchParams(url); Object.entries({ ...filters, ...change }).forEach(([key, value]) => value === undefined ? next.delete(key) : next.set(key, String(value))); setUrl(next, { replace: true }) }
  return <PermissionGuard permission={Permissions.Leaves.Manage} fallback={<UnauthorizedPage />}><div className="leave-page"><LeaveNavigation /><PageHeader eyebrow="Leave" title="Company Leave Requests" description="Review leave activity across your company." /><section className="leave-section"><div className="leave-section-heading"><div><h2>Company activity</h2><p>Search and review leave requests across employees and departments.</p></div>{query.data && <span className="section-meta">{query.data.totalCount} total</span>}</div><Card className="leave-surface"><CardContent><div className="toolbar leave-toolbar"><label className="leave-search">Search<input aria-label="Search company requests" value={search} onChange={(event) => setSearch(event.target.value)} onBlur={() => update({ search: search || undefined, page: 1 })} placeholder="Employee, request, or leave type" /></label><label>Status<select aria-label="Company status filter" value={filters.status ?? ''} onChange={(event) => update({ status: event.target.value ? Number(event.target.value) as LeaveRequestFilters['status'] : undefined, page: 1 })}><option value="">All statuses</option><option value="1">Pending</option><option value="2">Approved</option><option value="3">Declined</option><option value="4">Cancelled</option></select></label></div>{query.isPending ? <div className="leave-table-skeleton" role="status" aria-label="Loading company requests"><span /><span /><span /><span /></div> : query.isError ? <div className="inline-error" role="alert"><h2>Company requests could not be loaded</h2><p>Try again to refresh company activity.</p><button className="button button-secondary" onClick={() => void query.refetch()}>Retry</button></div> : query.data?.items.length ? <><LeaveRequestTable items={query.data.items} company /><div className="leave-pagination"><span>{query.data.totalCount} requests</span><span>Page {query.data.page} of {Math.max(1, query.data.totalPages)}</span></div></> : <div className="empty-state leave-empty"><h2>No Leave Requests found</h2><p>Try changing your search or status filter.</p></div>}</CardContent></Card></section></div></PermissionGuard>
}
