import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Button } from '../../../components/ui/Button'
import { Card, CardContent } from '../../../components/ui/Card'
import { PageHeader } from '../../../components/common/PageHeader'
import { LeaveApprovalTimeline } from '../components/LeaveApprovalTimeline'
import { LeaveNavigation } from '../components/LeaveNavigation'
import { LeaveRequestSummary } from '../components/LeaveRequestSummary'
import { useLeaveRequest } from '../hooks/useLeaveRequest'
import { useLeaveRequestMutations } from '../hooks/useLeaveRequestMutations'
import { toast } from 'sonner'

export function LeaveRequestDetailsPage() {
  const { leaveRequestId } = useParams(); const query = useLeaveRequest(leaveRequestId); const mutations = useLeaveRequestMutations(leaveRequestId); const navigate = useNavigate(); const [reason, setReason] = useState(''); const [comment, setComment] = useState('')
  if (query.isPending) return <p className="leave-loading" role="status">Loading request details…</p>
  if (query.isError || !query.data) return <div className="inline-error leave-page-message" role="alert"><h1>Leave request not found</h1><Link className="text-link" to="/leave">Back to My Leave</Link></div>
  const details = query.data
  return <div className="leave-page"><LeaveNavigation /><PageHeader eyebrow="Leave request" title={details.request.requestNumber ?? 'Request details'} description="Review request information and approval progress." /><div className="leave-detail-actions"><Link className="text-link" to="/leave">Back to My Leave</Link><div className="action-row">{details.canEdit && <Button variant="secondary" onClick={() => navigate(`/leave/${details.request.id}/edit`)}>Edit request</Button>}{details.canCancel && <><input aria-label="Cancellation reason" value={reason} maxLength={500} onChange={(event) => setReason(event.target.value)} placeholder="Optional cancellation reason" /><Button variant="ghost" disabled={mutations.cancel.isPending} onClick={() => { if (window.confirm(`Cancel ${details.request.requestNumber ?? 'this request'}? This action cannot be undone.`)) mutations.cancel.mutate({ id: details.request.id, reason }, { onSuccess: () => toast.success('Leave request cancelled.'), onError: () => toast.error('Cancellation is no longer available.') }) }}>Cancel request</Button></>}{details.canApprove && <Button disabled={mutations.approve.isPending} onClick={() => mutations.approve.mutate({ id: details.request.id, comment }, { onSuccess: () => toast.success('Leave request approved.'), onError: () => toast.error('This request is no longer actionable.') })}>Approve request</Button>}{details.canDecline && <><input aria-label="Decline comment" required maxLength={1000} value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Decline comment (required)" /><Button variant="ghost" disabled={!comment.trim() || mutations.decline.isPending} onClick={() => mutations.decline.mutate({ id: details.request.id, comment }, { onSuccess: () => toast.success('Leave request declined.'), onError: () => toast.error('This request is no longer actionable.') })}>Decline request</Button></>}</div></div><div className="leave-detail-grid"><Card className="leave-surface"><CardContent><div className="leave-section-heading"><div><h2>Request details</h2><p>Submitted request information.</p></div></div><LeaveRequestSummary details={details} /></CardContent></Card><Card className="leave-surface"><CardContent><div className="leave-section-heading"><div><h2>Approval progress</h2><p>Current workflow status and approver activity.</p></div></div><LeaveApprovalTimeline approvals={details.approvals} current={details.request.currentApprovalLevel} /></CardContent></Card></div></div>
}
