import { ArrowLeft } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Button } from '../../../components/ui/Button'
import { PermissionGuard } from '../../auth/components/PermissionGuard'
import { Permissions } from '../../../lib/permissions'
import { UnauthorizedPage } from '../../../pages/UnauthorizedPage'
import { useAssignment, useAssignmentOptions, useAttendanceConfigurationMutations } from '../hooks/useAttendanceConfiguration'
import { AttendancePageHeader, DateField, FormError, FormSurface, SelectField, Toggle } from '../components/AttendanceShared'
import type { EmployeeShiftAssignmentInput, UpdateEmployeeShiftAssignmentInput } from '../types/attendance.types'
import { toast } from 'sonner'

type AssignmentForm = { employeeId: string; workShiftId: string; effectiveFrom: string; effectiveTo: string; isActive: boolean; rowVersion: string }
const initial: AssignmentForm = { employeeId: '', workShiftId: '', effectiveFrom: '', effectiveTo: '', isActive: true, rowVersion: '' }

export function AssignmentFormPage() {
  const { assignmentId } = useParams(); const editing = Boolean(assignmentId); const navigate = useNavigate(); const query = useAssignment(assignmentId); const options = useAssignmentOptions(); const mutations = useAttendanceConfigurationMutations(); const [form, setForm] = useState(initial); const [error, setError] = useState(''); const set = (key: keyof AssignmentForm, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }))
  useEffect(() => { if (query.data) setForm({ employeeId: query.data.employee.id, workShiftId: query.data.workShift.id, effectiveFrom: query.data.effectiveFrom, effectiveTo: query.data.effectiveTo ?? '', isActive: query.data.isActive, rowVersion: query.data.rowVersion }) }, [query.data])
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); if (!form.employeeId || !form.workShiftId || !form.effectiveFrom) return setError('Employee, work shift, and effective-from date are required.'); if (form.effectiveTo && form.effectiveTo < form.effectiveFrom) return setError('Effective to must be on or after effective from.'); const base: EmployeeShiftAssignmentInput = { employeeId: form.employeeId, workShiftId: form.workShiftId, effectiveFrom: form.effectiveFrom, effectiveTo: form.effectiveTo || null }; try { if (editing && assignmentId) { const request: UpdateEmployeeShiftAssignmentInput = { ...base, isActive: form.isActive, rowVersion: form.rowVersion }; await mutations.updateAssignment.mutateAsync({ id: assignmentId, request }) } else await mutations.addAssignment.mutateAsync(base); toast.success(editing ? 'Shift assignment updated.' : 'Shift assignment added.'); navigate('/attendance/assignments') } catch (value) { setError((value as Error).message || 'The assignment could not be saved.') } }
  return <PermissionGuard permission={Permissions.Attendance.Manage} fallback={<UnauthorizedPage />}><div className="attendance-page"><AttendancePageHeader title={editing ? 'Edit Shift Assignment' : 'Assign Shift'} description="Set the effective date range for an employee schedule." action={<Link className="text-link" to="/attendance/assignments"><ArrowLeft size={15} /> Back to Assignments</Link>} />{(editing && query.isPending) || options.isPending ? <LoadingForm /> : <FormSurface><form className="attendance-form" onSubmit={(event) => void submit(event)} noValidate><FormError message={error} /><div className="attendance-form-section"><div><h2>Assignment details</h2><p>Only active employees and active shifts can be selected.</p></div><div className="attendance-form-grid"><SelectField label="Employee" value={form.employeeId} onChange={(value) => set('employeeId', value)} required><option value="">Select an employee</option>{(options.data?.employees ?? []).map((employee) => <option key={employee.id} value={employee.id}>{employee.employeeCode} · {employee.fullName}</option>)}</SelectField><SelectField label="Work shift" value={form.workShiftId} onChange={(value) => set('workShiftId', value)} required><option value="">Select a work shift</option>{(options.data?.workShifts ?? []).map((shift) => <option key={shift.id} value={shift.id}>{shift.code} · {shift.name}</option>)}</SelectField><DateField label="Effective from" value={form.effectiveFrom} onChange={(value) => set('effectiveFrom', value)} required /><DateField label="Effective to" value={form.effectiveTo} onChange={(value) => set('effectiveTo', value)} /></div></div>{editing && <div className="attendance-form-options"><Toggle label="Active" description="Inactive assignments remain available as history." checked={form.isActive} onChange={(value) => set('isActive', value)} /></div>}<div className="attendance-form-actions"><Button type="button" variant="secondary" onClick={() => navigate('/attendance/assignments')}>Cancel</Button><Button type="submit" disabled={mutations.addAssignment.isPending || mutations.updateAssignment.isPending}>{mutations.addAssignment.isPending || mutations.updateAssignment.isPending ? 'Saving…' : editing ? 'Save changes' : 'Assign Shift'}</Button></div></form></FormSurface>}</div></PermissionGuard>
}
function LoadingForm() { return <FormSurface><div className="attendance-loading" role="status"><span /><span /><span /></div></FormSurface> }
