import { ArrowLeft, CircleAlert, MapPin } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { Card, CardContent } from '../../../components/ui/Card'
import { PageHeader as AttendancePageHeader } from '../../../components/common/PageHeader'
import { PermissionGuard } from '../../auth/components/PermissionGuard'
import { Permissions } from '../../../lib/permissions'
import { UnauthorizedPage } from '../../../pages/UnauthorizedPage'
import { AttendanceStatusBadge } from '../components/AttendanceStatusBadge'
import { ErrorState, LoadingState } from '../components/AttendanceShared'
import { useAttendanceCorrectionOptions } from '../hooks/useAttendanceCorrections'
import { useMyAttendanceDetails } from '../hooks/useAttendanceEmployee'
import { formatDateOnly, formatDuration, formatUtc, sourceLabel } from '../utils/attendanceFormatters'

export function AttendanceDetailsPage() {
  const { attendanceRecordId } = useParams(); const query = useMyAttendanceDetails(attendanceRecordId); const correction = useAttendanceCorrectionOptions(attendanceRecordId)
  const action = correction.data?.hasPendingCorrection ? <Link className="button button-secondary" to={`/attendance/corrections/${correction.data.attendanceRecordId}`}>View pending correction</Link> : correction.data?.canRequestCorrection ? <Link className="button" to={`/attendance/corrections/new/${correction.data.attendanceRecordId}`}>Request correction</Link> : undefined
  return <PermissionGuard permission={Permissions.Attendance.View} fallback={<UnauthorizedPage />}><div className="attendance-page employee-attendance-page"><AttendancePageHeader title="Attendance details" description="Review the details recorded for this attendance event." action={<div className="attendance-detail-actions"><Link className="text-link" to="/attendance/history"><ArrowLeft size={15} /> Back to My Attendance</Link>{action}</div>} />{query.isPending ? <LoadingState label="Loading Attendance details" /> : query.isError ? <ErrorState title="Attendance details could not be loaded" error={query.error} retry={() => void query.refetch()} /> : !query.data ? <div className="alert alert-error"><CircleAlert size={17} />This attendance record was not found.</div> : <>{correction.data?.blockingReason && !correction.data.canRequestCorrection && <div className="alert alert-info" role="status"><CircleAlert size={17} />{correction.data.blockingReason}</div>}<div className="attendance-detail-grid"><Card><CardContent><div className="attendance-detail-header"><div><span className="attendance-local-date">{formatDateOnly(query.data.attendanceDate)}</span><h2>{query.data.shift?.code ?? 'Attendance event'}</h2><p>{query.data.shift?.name ?? 'No shift recorded'}</p></div><AttendanceStatusBadge status={query.data.status} /></div><dl className="attendance-detail-list"><Detail label="Source" value={sourceLabel(query.data.source)} /><Detail label="Scheduled start" value={formatUtc(query.data.scheduledStartDateTimeUtc)} /><Detail label="Scheduled end" value={formatUtc(query.data.scheduledEndDateTimeUtc)} /><Detail label="Check-In" value={formatUtc(query.data.checkInDateTimeUtc)} /><Detail label="Check-Out" value={formatUtc(query.data.checkOutDateTimeUtc)} /><Detail label="Late" value={query.data.lateMinutes ? `${query.data.lateMinutes} minutes` : 'On time'} /><Detail label="Early leave" value={query.data.checkOutDateTimeUtc ? `${query.data.earlyLeaveMinutes} minutes` : 'Not checked out'} /><Detail label="Work duration" value={query.data.checkOutDateTimeUtc ? formatDuration(query.data.workMinutes) : 'Not checked out'} /></dl></CardContent></Card><Card><CardContent><h2 className="attendance-detail-section-title">Attendance notes</h2><Detail label="Check-in remark" value={query.data.checkInRemark ?? '—'} /><Detail label="Check-out remark" value={query.data.checkOutRemark ?? '—'} /><Detail label="Manual adjustment" value={query.data.isManuallyAdjusted ? 'Yes' : 'No'} /><p className="attendance-detail-note"><MapPin size={15} />Location details remain attached to the original Attendance event.</p></CardContent></Card></div></>}</div></PermissionGuard>
}

function Detail({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div> }
