import { ArrowLeft } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Button } from '../../../components/ui/Button'
import { PermissionGuard } from '../../auth/components/PermissionGuard'
import { Permissions } from '../../../lib/permissions'
import { UnauthorizedPage } from '../../../pages/UnauthorizedPage'
import { useAttendanceConfigurationMutations, useLocation } from '../hooks/useAttendanceConfiguration'
import { AttendancePageHeader, Field, FormError, FormSurface, LocationHint, TextAreaField, Toggle } from '../components/AttendanceShared'
import type { AttendanceLocationInput, UpdateAttendanceLocationInput } from '../types/attendance.types'
import { toast } from 'sonner'

type LocationForm = { code: string; name: string; address: string; latitude: string; longitude: string; allowedRadiusMeters: string; isDefault: boolean; isActive: boolean; rowVersion: string }
const initial: LocationForm = { code: '', name: '', address: '', latitude: '', longitude: '', allowedRadiusMeters: '', isDefault: false, isActive: true, rowVersion: '' }

export function LocationFormPage() {
  const { locationId } = useParams(); const editing = Boolean(locationId); const navigate = useNavigate(); const query = useLocation(locationId); const mutations = useAttendanceConfigurationMutations(); const [form, setForm] = useState(initial); const [error, setError] = useState(''); const set = (key: keyof LocationForm, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }))
  useEffect(() => { if (query.data) setForm({ code: query.data.code, name: query.data.name, address: query.data.address ?? '', latitude: String(query.data.latitude), longitude: String(query.data.longitude), allowedRadiusMeters: String(query.data.allowedRadiusMeters), isDefault: query.data.isDefault, isActive: query.data.isActive, rowVersion: query.data.rowVersion }) }, [query.data])
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); const latitude = Number(form.latitude); const longitude = Number(form.longitude); const radius = Number(form.allowedRadiusMeters); if (!form.code.trim() || !form.name.trim()) return setError('Code and name are required.'); if (!form.latitude || !form.longitude || !Number.isFinite(latitude) || !Number.isFinite(longitude)) return setError('Latitude and longitude must be valid numbers.'); if (latitude < -90 || latitude > 90 || longitude < -180 || longitude > 180) return setError('Latitude must be between -90 and 90 and longitude between -180 and 180.'); if (!form.allowedRadiusMeters || !Number.isFinite(radius) || radius <= 0 || radius > 100000) return setError('Allowed radius must be greater than 0 and no more than 100000 meters.'); const base: AttendanceLocationInput = { code: form.code.trim().toUpperCase(), name: form.name.trim(), address: form.address.trim() || null, latitude, longitude, allowedRadiusMeters: radius, isDefault: form.isDefault }; try { if (editing && locationId) { const request: UpdateAttendanceLocationInput = { ...base, isActive: form.isActive, rowVersion: form.rowVersion }; await mutations.updateLocation.mutateAsync({ id: locationId, request }) } else await mutations.addLocation.mutateAsync(base); toast.success(editing ? 'Attendance location updated.' : 'Attendance location added.'); navigate('/attendance/locations') } catch (value) { setError((value as Error).message || 'The attendance location could not be saved.') } }
  return <PermissionGuard permission={Permissions.Attendance.Manage} fallback={<UnauthorizedPage />}><div className="attendance-page"><AttendancePageHeader title={editing ? 'Edit Attendance Location' : 'Add Attendance Location'} description="Define where location-aware attendance can be recorded." action={<Link className="text-link" to="/attendance/locations"><ArrowLeft size={15} /> Back to Locations</Link>} />{editing && query.isPending ? <div className="attendance-loading" /> : <FormSurface><form className="attendance-form" onSubmit={(event) => void submit(event)} noValidate><FormError message={error} /><div className="attendance-form-section"><div><h2>Location identity</h2><p>Keep the name recognizable to employees and administrators.</p></div><div className="attendance-form-grid"><Field label="Code" value={form.code} onChange={(value) => set('code', value)} required /><Field label="Name" value={form.name} onChange={(value) => set('name', value)} required /><TextAreaField label="Address" value={form.address} onChange={(value) => set('address', value)} /></div></div><div className="attendance-form-section"><div><h2>Coordinates and radius</h2><p>Coordinates are stored as numeric decimal values.</p></div><div className="attendance-form-grid"><Field label="Latitude" value={form.latitude} onChange={(value) => set('latitude', value)} type="number" step="any" min={-90} max={90} required /><Field label="Longitude" value={form.longitude} onChange={(value) => set('longitude', value)} type="number" step="any" min={-180} max={180} required /><Field label="Allowed radius (meters)" value={form.allowedRadiusMeters} onChange={(value) => set('allowedRadiusMeters', value)} type="number" step="0.01" min={0.01} max={100000} required /><LocationHint /></div></div><div className="attendance-form-options"><Toggle label="Default location" description="Use this location as the company default when applicable." checked={form.isDefault} onChange={(value) => set('isDefault', value)} />{editing && <Toggle label="Active" description="Inactive locations cannot be selected for new attendance events." checked={form.isActive} onChange={(value) => set('isActive', value)} />}</div><div className="attendance-form-actions"><Button type="button" variant="secondary" onClick={() => navigate('/attendance/locations')}>Cancel</Button><Button type="submit" disabled={mutations.addLocation.isPending || mutations.updateLocation.isPending}>{mutations.addLocation.isPending || mutations.updateLocation.isPending ? 'Saving…' : editing ? 'Save changes' : 'Add Location'}</Button></div></form></FormSurface>}</div></PermissionGuard>
}
